# Generated by Django 6.0.2 on 2026-02-17 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_inquiry_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Inquiries'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(default='I am interested in this property. Please contact me with more details.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
