# Generated by Django 6.0.2 on 2026-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single_room', 'Single Room'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedroom'), ('three_bedroom', '3 Bedroom'), ('studio', 'Studio'), ('mansionette', 'Mansionette')], default='bedsitter', max_length=20),
        ),
    ]
